project_id = "tqagkqiodmegvfdycwtq"

[functions.seed-users]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.initialize-payment]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false
